# Generated by Django 3.2.25 on 2025-09-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='avatars/default.png', help_text='Upload a profile picture (JPG, PNG, GIF, WebP up to 5MB)', upload_to='avatars/'),
        ),
    ]
