# Generated by Django 3.2.25 on 2025-10-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_orderlineitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('cancelled', 'Cancelled')], default='pending', help_text='Current payment status of the order', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount refunded (if any)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when refund was processed', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_charge_id',
            field=models.CharField(blank=True, help_text='Stripe Charge ID for successful payments', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID for tracking payments', max_length=254, null=True),
        ),
    ]
