# Generated by Django 3.2.25 on 2025-10-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20251002_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current payment status of the order', max_length=20),
        ),
    ]
