# Generated by Django 3.2.25 on 2025-10-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20251002_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_charge_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent_id',
        ),
    ]
