# Generated by Django 3.2.25 on 2025-06-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='downloads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='download', to='products.product')),
            ],
        ),
    ]
