# Generated by Django 3.2.25 on 2025-06-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaldownload',
            name='file',
            field=models.FileField(max_length=1000, upload_to='downloads/'),
        ),
    ]
