# Generated by Django 3.2.25 on 2025-10-02 12:42

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_digitaldownload_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaldownload',
            name='file',
            field=models.FileField(max_length=500, storage=catalogue.models.get_digital_download_storage, upload_to='digital_downloads/'),
        ),
    ]
