# Generated by Django 5.0.14 on 2025-05-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_is_creator_product_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='license_number',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
    ]
