# Generated by Django 5.0.14 on 2025-05-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_license_number_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='license_number',
            new_name='model_number',
        ),
    ]
